### PR TITLE
Fix issue with method defaults

### LINKED ISSUE #434: Overriding approval methods clears all defaults
We had a problem today where a policy added alternate comments for some rules, but expected the default behavior of counting GitHub reviews to still work. With the current implementation, setting any property of the `methods` block removes the defaults for all properties.

Consider setting defaults for fields that are not explicitly set by the policy file to reduce confusion, as the docs imply.

### PR DESCRIPTION
**Pull request by shravan1k**
When certain attributes are defined under 'methods', the other undefined attributes don't line up with the promised defaults. This PR resolves this issue by checking whether certain attributes were not specified and then adds defaults for them.

Closes #434

### CODE REVIEW

File: policy/approval/approve.go [hunk 1]
```diff
@@ -57,13 +57,24 @@ type RequestReview struct {
...
 		methods = &common.Methods{
 			Comments: []string{
 				":+1:",
 				"👍",
 			},
-			GithubReview: true,
+			GithubReview: &defaultBool,
+		}
+	} else {
+		if len(methods.Comments) == 0 {
```
Comment (asvoboda) [inline policy/approval/approve.go]: I think you could simplify both the if and the else into one. Effectively, if `methods == nil`, then `methods.Comments` and `methods.GithubReview` will also be nil.

File: policy/common/methods.go [hunk 2]
```diff
@@ -25,7 +25,7 @@ import (
 type Methods struct {
 	Comments                    []string `yaml:"comments,omitempty"`
 	CommentPatterns             []Regexp `yaml:"comment_patterns,omitempty"`
-	GithubReview                bool     `yaml:"github_review,omitempty"`
+	GithubReview                *bool    `yaml:"github_review,omitempty"`
```
Comment (asvoboda) [inline policy/common/methods.go:28]: Is the idea here that this is changed to a pointer to signal the difference between unset vs default false?

Comment (shravan1k) [reply policy/common/methods.go:28]: Yeah

File: policy/approval/approve.go (hunk 1 above)
Comment (shravan1k) [reply policy/approval/approve.go]: I agree, will make the change.

File: policy/approval/approve.go [hunk 3]
```diff
@@ -57,15 +57,19 @@ type RequestReview struct {
 
 func (opts *Options) GetMethods() *common.Methods {
 	methods := opts.Methods
+	defaultBool := true
```
Comment (derekjobst) [inline policy/approval/approve.go]: Let's use a more descriptive name here and in the other instances where `defaultBool` has been added. Perhaps `defaultGithubReview`?

File: policy/approval/approve.go [hunk 4]
```diff
@@ -57,15 +57,19 @@ type RequestReview struct {
...
-				":+1:",
-				"👍",
-			},
-			GithubReview: true,
+		methods = &common.Methods{}
+	}
+	if len(methods.Comments) == 0 {
+		methods.Comments = []string{
+			":+1:",
+			"👍",
```
Comment (derekjobst) [inline policy/approval/approve.go:66]: Will this allow a policy to be configured without comment approvals? In other words, will it still be possible to configure a policy where only github reviews (i.e. `github_review=true`) are acceptable forms of approval?

Comment (shravan1k) [reply policy/approval/approve.go:66]: Good catch. New commit resolves this.

File: policy/common/methods.go [hunk 5]
```diff
@@ -23,10 +23,10 @@ import (
 )
 
 type Methods struct {
-	Comments                    []string `yaml:"comments,omitempty"`
-	CommentPatterns             []Regexp `yaml:"comment_patterns,omitempty"`
-	GithubReview                bool     `yaml:"github_review,omitempty"`
-	GithubReviewCommentPatterns []Regexp `yaml:"github_review_comment_patterns,omitempty"`
+	Comments                    *[]string `yaml:"comments,omitempty"`
```
Comment (bluekeyes) [inline policy/common/methods.go]: Making this a pointer is not necessary. In Go, slices implicitly work like pointers but we don't usually think about it because a `nil` slice behaves the same as a non-`nil` empty slice. When a user does not specify the `comments` field in configuration, the value will be `nil`.

File: policy/approval/approve.go [hunk 6]
```diff
@@ -82,10 +87,10 @@ func (r *Rule) Trigger() common.Trigger {
 
 	if r.Requires.Count > 0 {
 		m := r.Options.GetMethods()
-		if len(m.Comments) > 0 || len(m.CommentPatterns) > 0 {
+		if m.Comments != nil && len(*m.Comments) > 0 || len(m.CommentPatterns) > 0 {
```
Comment (bluekeyes) [inline policy/approval/approve.go]: These `nil` checks and dereferencing are not necessary once `m.Comments` is reverted back to a `[]string` because `len(nil) == 0`

File: policy/common/methods.go [hunk 7]
```diff
@@ -120,9 +120,11 @@ func deduplicateCandidates(all []*Candidate) []*Candidate {
 }
 
 func (m *Methods) CommentMatches(commentBody string) bool {
-	for _, comment := range m.Comments {
-		if strings.Contains(commentBody, comment) {
-			return true
+	if m.Comments != nil {
```
Comment (bluekeyes) [inline policy/common/methods.go]: Same idea here with the nil check and dereferencing: you can `range` over a `nil` slice without checking first.

**Review by bluekeyes — COMMENTED** [review]
One comment about the slice handling, but otherwise this looks good.

We'll want to be careful about noting this in the release notes because it is technically a breaking change. As Derek alluded to, if I have a policy like:

```yaml
options:
  methods:
    github_review: true
```

it currently disables comments. In order to keep the same behavior after this PR, I'll have to change the policy to:

```yaml
options:
  methods:
    comments: []
    github_review:  true
```

This is consistent with what the docs have always claimed, so I'd count this a bug fix, but people might have been relying on the old broken behavior. We might want to audit at least our internal policies to see if this will impact anything.

File: policy/common/methods.go (hunk 5 above)
Comment (shravan1k) [reply policy/common/methods.go]: Makes sense. Will revert that back.

**Review by bluekeyes — APPROVED** [review]
