### PR TITLE
Load app name from GitHub dynamically

### LINKED ISSUE #207: Load app name from GitHub
There's no reason to include the `app_name` key in the server configuration, since the app can look this up dynamically from GitHub. Since policy-bot posts failed statuses when the name in the config doesn't match the name in GitHub, this option leads to confusion, for example #206, #107, and #72.

Using the `app_name` may also be unnecessary if we switch to IDs for auditing, per #109.

### PR DESCRIPTION
**Pull request by bluekeyes**
The 'options.app_name' server configuration value is now deprecated and ignored. The struct field is still defined to avoid breaking configuration when using UnmarshalStrict.

Fixes #207.

### CODE REVIEW

**Review by asvoboda — APPROVED** [review]

File: server/server.go [hunk 1]
```diff
@@ -91,7 +92,7 @@ func New(c *Config) (*Server, error) {
 		githubTimeout = 10 * time.Second
 	}
 
-	userAgent := fmt.Sprintf("%s/%s", c.Options.AppName, version.GetVersion())
+	userAgent := fmt.Sprintf("policy-bot/%s", version.GetVersion())
```
Comment (bluekeyes) [inline server/server.go:95]: Using the app name here requires creating a separate app client and didn't seem worth it. I think `policy-bot` is an appropriate user agent in most cases, even if the app is registered with a different name.

**Comment by ekosz** [comment]
Hi there. This is a great change and something we've been struggling to override in out k8s cluster (can't quite get the mounting of our config file working). Do you all have a plan release date in mind for this?

**Comment by bluekeyes** [comment]
I hope to have a release with this by the end of the week, either as 1.19.2 or as part of a larger 1.20.0 release with some other changes I'm working on.

We also publish a `snapshot` tag to Docker Hub from the `develop` branch if you want to try this before the release is out.
